// Popular anime fetched from Jikan API
// This list is used for SSG pre-rendering and SEO metadata
// Last updated: 150 anime from top anime, airing, and movie lists

export interface StaticAnime {
  id: number
  title: string
  slug: string
  genres: string[]
  type: string
  status: string
  year?: number | string
}

export const STATIC_ANIME_LIST: StaticAnime[] = [
  {
    id: 52991,
    title: "Sousou no Frieren",
    slug: "sousou-no-frieren",
    genres: ["Adventure", "Drama", "Fantasy"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 59978,
    title: "Sousou no Frieren 2nd Season",
    slug: "sousou-no-frieren-2nd-season",
    genres: ["Adventure", "Drama", "Fantasy"],
    type: "TV",
    status: "Currently Airing",
    year: 2026,
  },
  {
    id: 5114,
    title: "Fullmetal Alchemist: Brotherhood",
    slug: "fullmetal-alchemist-brotherhood",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    type: "TV",
    status: "Finished Airing",
    year: 2009,
  },
  {
    id: 57555,
    title: "Chainsaw Man Movie: Reze-hen",
    slug: "chainsaw-man-movie-reze-hen",
    genres: ["Action", "Fantasy"],
    type: "Movie",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 9253,
    title: "Steins;Gate",
    slug: "steinsgate",
    genres: ["Drama", "Sci-Fi", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2011,
  },
  {
    id: 38524,
    title: "Shingeki no Kyojin Season 3 Part 2",
    slug: "shingeki-no-kyojin-season-3-part-2",
    genres: ["Action", "Drama", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2019,
  },
  {
    id: 28977,
    title: "Gintama°",
    slug: "gintama",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2015,
  },
  {
    id: 39486,
    title: "Gintama: The Final",
    slug: "gintama-the-final",
    genres: ["Action", "Comedy", "Drama", "Sci-Fi"],
    type: "Movie",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 11061,
    title: "Hunter x Hunter (2011)",
    slug: "hunter-x-hunter-2011",
    genres: ["Action", "Adventure", "Fantasy"],
    type: "TV",
    status: "Finished Airing",
    year: 2011,
  },
  {
    id: 60022,
    title: "One Piece Fan Letter",
    slug: "one-piece-fan-letter",
    genres: ["Action", "Adventure", "Fantasy"],
    type: "TV Special",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 9969,
    title: "Gintama'",
    slug: "gintama",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2011,
  },
  {
    id: 15417,
    title: "Gintama': Enchousen",
    slug: "gintama-enchousen",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2012,
  },
  {
    id: 820,
    title: "Ginga Eiyuu Densetsu",
    slug: "ginga-eiyuu-densetsu",
    genres: ["Drama", "Sci-Fi"],
    type: "OVA",
    status: "Finished Airing",
    year: 1988,
  },
  {
    id: 34096,
    title: "Gintama.",
    slug: "gintama",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 41467,
    title: "Bleach: Sennen Kessen-hen",
    slug: "bleach-sennen-kessen-hen",
    genres: ["Action", "Adventure", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 43608,
    title: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    slug: "kaguya-sama-wa-kokurasetai-ultra-romantic",
    genres: ["Comedy", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 42938,
    title: "Fruits Basket: The Final",
    slug: "fruits-basket-the-final",
    genres: ["Drama", "Romance", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 4181,
    title: "Clannad: After Story",
    slug: "clannad-after-story",
    genres: ["Drama", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2008,
  },
  {
    id: 918,
    title: "Gintama",
    slug: "gintama",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2006,
  },
  {
    id: 28851,
    title: "Koe no Katachi",
    slug: "koe-no-katachi",
    genres: ["Award Winning", "Drama"],
    type: "Movie",
    status: "Finished Airing",
    year: 2016,
  },
  {
    id: 58514,
    title: "Kusuriya no Hitorigoto 2nd Season",
    slug: "kusuriya-no-hitorigoto-2nd-season",
    genres: ["Drama", "Mystery"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 2904,
    title: "Code Geass: Hangyaku no Lelouch R2",
    slug: "code-geass-hangyaku-no-lelouch-r2",
    genres: ["Award Winning", "Drama", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2008,
  },
  {
    id: 35180,
    title: "3-gatsu no Lion 2nd Season",
    slug: "3-gatsu-no-lion-2nd-season",
    genres: ["Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 15335,
    title: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare",
    slug: "gintama-movie-2-kanketsu-hen-yorozuya-yo-eien-nare",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "Movie",
    status: "Finished Airing",
    year: 2013,
  },
  {
    id: 19,
    title: "Monster",
    slug: "monster",
    genres: ["Drama", "Mystery", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2004,
  },
  {
    id: 37491,
    title: "Gintama. Shirogane no Tamashii-hen - Kouhan-sen",
    slug: "gintama-shirogane-no-tamashii-hen-kouhan-sen",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 51535,
    title: "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
    slug: "shingeki-no-kyojin-the-final-season-kanketsu-hen",
    genres: ["Action", "Drama", "Suspense"],
    type: "TV Special",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 35247,
    title: "Owarimonogatari 2nd Season",
    slug: "owarimonogatari-2nd-season",
    genres: ["Comedy", "Mystery", "Supernatural"],
    type: "TV Special",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 54492,
    title: "Kusuriya no Hitorigoto",
    slug: "kusuriya-no-hitorigoto",
    genres: ["Drama", "Mystery"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 40682,
    title: "Kingdom 3rd Season",
    slug: "kingdom-3rd-season",
    genres: ["Action"],
    type: "TV",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 37987,
    title: "Violet Evergarden Movie",
    slug: "violet-evergarden-movie",
    genres: ["Award Winning", "Drama"],
    type: "Movie",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 59571,
    title: "Shingeki no Kyojin Movie: Kanketsu-hen - The Last Attack",
    slug: "shingeki-no-kyojin-movie-kanketsu-hen-the-last-attack",
    genres: ["Action", "Drama", "Suspense"],
    type: "Movie",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 32281,
    title: "Kimi no Na wa.",
    slug: "kimi-no-na-wa",
    genres: ["Award Winning", "Drama"],
    type: "Movie",
    status: "Finished Airing",
    year: 2016,
  },
  {
    id: 49387,
    title: "Vinland Saga Season 2",
    slug: "vinland-saga-season-2",
    genres: ["Action", "Adventure", "Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 36838,
    title: "Gintama. Shirogane no Tamashii-hen",
    slug: "gintama-shirogane-no-tamashii-hen",
    genres: ["Action", "Comedy", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 37510,
    title: "Mob Psycho 100 II",
    slug: "mob-psycho-100-ii",
    genres: ["Action", "Comedy", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2019,
  },
  {
    id: 31758,
    title: "Kizumonogatari III: Reiketsu-hen",
    slug: "kizumonogatari-iii-reiketsu-hen",
    genres: ["Action", "Mystery", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 2921,
    title: "Ashita no Joe 2",
    slug: "ashita-no-joe-2",
    genres: ["Drama", "Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 1980,
  },
  {
    id: 40028,
    title: "Shingeki no Kyojin: The Final Season",
    slug: "shingeki-no-kyojin-the-final-season",
    genres: ["Action", "Drama", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 37521,
    title: "Vinland Saga",
    slug: "vinland-saga",
    genres: ["Action", "Adventure", "Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2019,
  },
  {
    id: 263,
    title: "Hajime no Ippo",
    slug: "hajime-no-ippo",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2000,
  },
  {
    id: 32935,
    title: "Haikyuu!! Karasuno Koukou vs. Shiratorizawa Gakuen Koukou",
    slug: "haikyuu-karasuno-koukou-vs-shiratorizawa-gakuen-koukou",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2016,
  },
  {
    id: 199,
    title: "Sen to Chihiro no Kamikakushi",
    slug: "sen-to-chihiro-no-kamikakushi",
    genres: ["Adventure", "Award Winning", "Fantasy"],
    type: "Movie",
    status: "Finished Airing",
    year: 2001,
  },
  {
    id: 48583,
    title: "Shingeki no Kyojin: The Final Season Part 2",
    slug: "shingeki-no-kyojin-the-final-season-part-2",
    genres: ["Action", "Drama", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 60489,
    title: "Takopii no Genzai",
    slug: "takopii-no-genzai",
    genres: ["Drama", "Sci-Fi"],
    type: "ONA",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 17074,
    title: "Monogatari Series: Second Season",
    slug: "monogatari-series-second-season",
    genres: ["Comedy", "Mystery", "Romance", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2013,
  },
  {
    id: 1,
    title: "Cowboy Bebop",
    slug: "cowboy-bebop",
    genres: ["Action", "Award Winning", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 1998,
  },
  {
    id: 60098,
    title: "Boku no Hero Academia: Final Season",
    slug: "boku-no-hero-academia-final-season",
    genres: ["Action"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 53223,
    title: "Kingdom 5th Season",
    slug: "kingdom-5th-season",
    genres: ["Action"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 47917,
    title: "Bocchi the Rock!",
    slug: "bocchi-the-rock",
    genres: ["Comedy"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 50160,
    title: "Kingdom 4th Season",
    slug: "kingdom-4th-season",
    genres: ["Action"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 21,
    title: "One Piece",
    slug: "one-piece",
    genres: ["Action", "Adventure", "Fantasy"],
    type: "TV",
    status: "Currently Airing",
    year: 1999,
  },
  {
    id: 52198,
    title: "Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai",
    slug: "kaguya-sama-wa-kokurasetai-first-kiss-wa-owaranai",
    genres: ["Comedy", "Drama", "Romance"],
    type: "Movie",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 39894,
    title: "Hibike! Euphonium 3",
    slug: "hibike-euphonium-3",
    genres: ["Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 24701,
    title: "Mushishi Zoku Shou 2nd Season",
    slug: "mushishi-zoku-shou-2nd-season",
    genres: ["Adventure", "Mystery", "Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2014,
  },
  {
    id: 48569,
    title: "86 Part 2",
    slug: "86-part-2",
    genres: ["Drama", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 52215,
    title: "Chi. Chikyuu no Undou ni Tsuite",
    slug: "chi-chikyuu-no-undou-ni-tsuite",
    genres: ["Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 1575,
    title: "Code Geass: Hangyaku no Lelouch",
    slug: "code-geass-hangyaku-no-lelouch",
    genres: ["Award Winning", "Drama", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2006,
  },
  {
    id: 45649,
    title: "The First Slam Dunk",
    slug: "the-first-slam-dunk",
    genres: ["Award Winning", "Sports"],
    type: "Movie",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 50172,
    title: "Mob Psycho 100 III",
    slug: "mob-psycho-100-iii",
    genres: ["Action", "Comedy", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 44074,
    title: "Shiguang Dailiren",
    slug: "shiguang-dailiren",
    genres: ["Drama", "Mystery", "Suspense"],
    type: "ONA",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 51009,
    title: "Jujutsu Kaisen 2nd Season",
    slug: "jujutsu-kaisen-2nd-season",
    genres: ["Action", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 55690,
    title: "Boku no Kokoro no Yabai Yatsu 2nd Season",
    slug: "boku-no-kokoro-no-yabai-yatsu-2nd-season",
    genres: ["Comedy", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 55016,
    title: "Idol",
    slug: "idol",
    genres: [],
    type: "Music",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 53998,
    title: "Bleach: Sennen Kessen-hen - Ketsubetsu-tan",
    slug: "bleach-sennen-kessen-hen-ketsubetsu-tan",
    genres: ["Action", "Adventure", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 33095,
    title: "Shouwa Genroku Rakugo Shinjuu: Sukeroku Futatabi-hen",
    slug: "shouwa-genroku-rakugo-shinjuu-sukeroku-futatabi-hen",
    genres: ["Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 47778,
    title: "Kimetsu no Yaiba: Yuukaku-hen",
    slug: "kimetsu-no-yaiba-yuukaku-hen",
    genres: ["Action", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 61517,
    title: "Kingdom 6th Season",
    slug: "kingdom-6th-season",
    genres: ["Action"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 53447,
    title: "Tu Bian Yingxiong X",
    slug: "tu-bian-yingxiong-x",
    genres: ["Action"],
    type: "ONA",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 33352,
    title: "Violet Evergarden",
    slug: "violet-evergarden",
    genres: ["Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 44,
    title: "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen",
    slug: "rurouni-kenshin-meiji-kenkaku-romantan-tsuioku-hen",
    genres: ["Action", "Drama", "Romance"],
    type: "OVA",
    status: "Finished Airing",
    year: 1999,
  },
  {
    id: 59192,
    title: "Kimetsu no Yaiba Movie 1: Mugenjou-hen - Akaza Sairai",
    slug: "kimetsu-no-yaiba-movie-1-mugenjou-hen-akaza-sairai",
    genres: ["Action", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 21939,
    title: "Mushishi Zoku Shou",
    slug: "mushishi-zoku-shou",
    genres: ["Adventure", "Mystery", "Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2014,
  },
  {
    id: 245,
    title: "Great Teacher Onizuka",
    slug: "great-teacher-onizuka",
    genres: ["Comedy"],
    type: "TV",
    status: "Finished Airing",
    year: 1999,
  },
  {
    id: 61930,
    title: "Uma Musume: Cinderella Gray Part 2",
    slug: "uma-musume-cinderella-gray-part-2",
    genres: ["Drama", "Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 58788,
    title: "Ikoku Nikki",
    slug: "ikoku-nikki",
    genres: ["Drama"],
    type: "TV",
    status: "Currently Airing",
    year: 2026,
  },
  {
    id: 56784,
    title: "Bleach: Sennen Kessen-hen - Soukoku-tan",
    slug: "bleach-sennen-kessen-hen-soukoku-tan",
    genres: ["Action", "Adventure", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 5258,
    title: "Hajime no Ippo: New Challenger",
    slug: "hajime-no-ippo-new-challenger",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2009,
  },
  {
    id: 431,
    title: "Howl no Ugoku Shiro",
    slug: "howl-no-ugoku-shiro",
    genres: ["Adventure", "Award Winning", "Drama", "Fantasy", "Romance"],
    type: "Movie",
    status: "Finished Airing",
    year: 2004,
  },
  {
    id: 164,
    title: "Mononoke Hime",
    slug: "mononoke-hime",
    genres: ["Action", "Adventure", "Award Winning", "Fantasy"],
    type: "Movie",
    status: "Finished Airing",
    year: 1997,
  },
  {
    id: 40434,
    title: "Mo Dao Zu Shi: Wanjie Pian",
    slug: "mo-dao-zu-shi-wanjie-pian",
    genres: ["Action", "Adventure", "Drama", "Fantasy", "Mystery"],
    type: "ONA",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 57864,
    title: "Monogatari Series: Off & Monster Season",
    slug: "monogatari-series-off-monster-season",
    genres: ["Comedy", "Mystery", "Supernatural"],
    type: "ONA",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 57647,
    title: "Uma Musume: Pretty Derby - Shin Jidai no Tobira",
    slug: "uma-musume-pretty-derby-shin-jidai-no-tobira",
    genres: ["Sports"],
    type: "Movie",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 457,
    title: "Mushishi",
    slug: "mushishi",
    genres: ["Adventure", "Mystery", "Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2005,
  },
  {
    id: 33050,
    title: "Fate/stay night Movie: Heaven's Feel - III. Spring Song",
    slug: "fatestay-night-movie-heavens-feel-iii-spring-song",
    genres: ["Action", "Fantasy"],
    type: "Movie",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 2001,
    title: "Tengen Toppa Gurren Lagann",
    slug: "tengen-toppa-gurren-lagann",
    genres: ["Adventure", "Award Winning", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2007,
  },
  {
    id: 49413,
    title: "Shiguang Dailiren II",
    slug: "shiguang-dailiren-ii",
    genres: ["Drama", "Mystery", "Suspense"],
    type: "ONA",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 23273,
    title: "Shigatsu wa Kimi no Uso",
    slug: "shigatsu-wa-kimi-no-uso",
    genres: ["Drama", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2014,
  },
  {
    id: 50399,
    title: "Tian Guan Cifu Er",
    slug: "tian-guan-cifu-er",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    type: "ONA",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 35760,
    title: "Shingeki no Kyojin Season 3",
    slug: "shingeki-no-kyojin-season-3",
    genres: ["Action", "Drama", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 55255,
    title: "Alien Stage",
    slug: "alien-stage",
    genres: ["Drama", "Sci-Fi", "Suspense"],
    type: "Music",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 34599,
    title: "Made in Abyss",
    slug: "made-in-abyss",
    genres: ["Adventure", "Drama", "Fantasy", "Mystery", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 11665,
    title: "Natsume Yuujinchou Shi",
    slug: "natsume-yuujinchou-shi",
    genres: ["Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2012,
  },
  {
    id: 22135,
    title: "Ping Pong the Animation",
    slug: "ping-pong-the-animation",
    genres: ["Award Winning", "Drama", "Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2014,
  },
  {
    id: 46102,
    title: "Odd Taxi",
    slug: "odd-taxi",
    genres: ["Award Winning", "Drama", "Mystery", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 58125,
    title: "Look Back",
    slug: "look-back",
    genres: ["Drama"],
    type: "Movie",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 49818,
    title: "Guimi Zhi Zhu: Xiaochou Pian",
    slug: "guimi-zhi-zhu-xiaochou-pian",
    genres: ["Action", "Fantasy", "Mystery", "Suspense"],
    type: "ONA",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 42310,
    title: "Cyberpunk: Edgerunners",
    slug: "cyberpunk-edgerunners",
    genres: ["Action", "Sci-Fi"],
    type: "ONA",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 1535,
    title: "Death Note",
    slug: "death-note",
    genres: ["Supernatural", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2006,
  },
  {
    id: 28891,
    title: "Haikyuu!! Second Season",
    slug: "haikyuu-second-season",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2015,
  },
  {
    id: 61952,
    title: "Luo Xiaohei Zhanji 2",
    slug: "luo-xiaohei-zhanji-2",
    genres: ["Adventure", "Drama", "Fantasy"],
    type: "Movie",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 54898,
    title: "Bungou Stray Dogs 5th Season",
    slug: "bungou-stray-dogs-5th-season",
    genres: ["Action", "Mystery"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 52742,
    title: "Haikyuu!! Movie: Gomisuteba no Kessen",
    slug: "haikyuu-movie-gomisuteba-no-kessen",
    genres: ["Sports"],
    type: "Movie",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 34591,
    title: "Natsume Yuujinchou Roku",
    slug: "natsume-yuujinchou-roku",
    genres: ["Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 4565,
    title: "Tengen Toppa Gurren Lagann Movie 2: Lagann-hen",
    slug: "tengen-toppa-gurren-lagann-movie-2-lagann-hen",
    genres: ["Sci-Fi"],
    type: "Movie",
    status: "Finished Airing",
    year: 2009,
  },
  {
    id: 40591,
    title: "Kaguya-sama wa Kokurasetai? Tensai-tachi no Renai Zunousen",
    slug: "kaguya-sama-wa-kokurasetai-tensai-tachi-no-renai-zunousen",
    genres: ["Comedy", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 45576,
    title: "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
    slug: "mushoku-tensei-isekai-ittara-honki-dasu-part-2",
    genres: ["Adventure", "Drama", "Fantasy", "Ecchi"],
    type: "TV",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 19647,
    title: "Hajime no Ippo: Rising",
    slug: "hajime-no-ippo-rising",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2013,
  },
  {
    id: 33,
    title: "Kenpuu Denki Berserk",
    slug: "kenpuu-denki-berserk",
    genres: ["Action", "Adventure", "Drama", "Fantasy", "Horror"],
    type: "TV",
    status: "Finished Airing",
    year: 1997,
  },
  {
    id: 36862,
    title: "Made in Abyss Movie 3: Fukaki Tamashii no Reimei",
    slug: "made-in-abyss-movie-3-fukaki-tamashii-no-reimei",
    genres: ["Adventure", "Drama", "Fantasy", "Mystery", "Sci-Fi"],
    type: "Movie",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 41084,
    title: "Made in Abyss: Retsujitsu no Ougonkyou",
    slug: "made-in-abyss-retsujitsu-no-ougonkyou",
    genres: ["Adventure", "Drama", "Fantasy", "Mystery", "Sci-Fi"],
    type: "TV",
    status: "Finished Airing",
    year: 2022,
  },
  {
    id: 52701,
    title: "Dungeon Meshi",
    slug: "dungeon-meshi",
    genres: ["Adventure", "Comedy", "Fantasy", "Gourmet"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 38329,
    title: "Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai",
    slug: "seishun-buta-yarou-wa-yumemiru-shoujo-no-yume-wo-minai",
    genres: ["Drama", "Romance", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2019,
  },
  {
    id: 7311,
    title: "Suzumiya Haruhi no Shoushitsu",
    slug: "suzumiya-haruhi-no-shoushitsu",
    genres: ["Award Winning", "Mystery", "Sci-Fi", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2010,
  },
  {
    id: 57658,
    title: "Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen",
    slug: "jujutsu-kaisen-shimetsu-kaiyuu-zenpen",
    genres: ["Action", "Supernatural"],
    type: "TV",
    status: "Currently Airing",
    year: 2026,
  },
  {
    id: 55823,
    title: "Natsume Yuujinchou Shichi",
    slug: "natsume-yuujinchou-shichi",
    genres: ["Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2024,
  },
  {
    id: 3786,
    title: "Shin Evangelion Movie:||",
    slug: "shin-evangelion-movie",
    genres: ["Award Winning", "Drama", "Sci-Fi", "Suspense"],
    type: "Movie",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 37991,
    title: "JoJo no Kimyou na Bouken Part 5: Ougon no Kaze",
    slug: "jojo-no-kimyou-na-bouken-part-5-ougon-no-kaze",
    genres: ["Action", "Adventure"],
    type: "TV",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 28957,
    title: "Mushishi Zoku Shou: Suzu no Shizuku",
    slug: "mushishi-zoku-shou-suzu-no-shizuku",
    genres: ["Adventure", "Mystery", "Slice of Life", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2015,
  },
  {
    id: 59636,
    title: "Uma Musume: Cinderella Gray",
    slug: "uma-musume-cinderella-gray",
    genres: ["Drama", "Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 58567,
    title: "Ore dake Level Up na Ken Season 2: Arise from the Shadow",
    slug: "ore-dake-level-up-na-ken-season-2-arise-from-the-shadow",
    genres: ["Action", "Adventure", "Fantasy"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 16498,
    title: "Shingeki no Kyojin",
    slug: "shingeki-no-kyojin",
    genres: ["Action", "Award Winning", "Drama", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2013,
  },
  {
    id: 877,
    title: "Nana",
    slug: "nana",
    genres: ["Drama", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2006,
  },
  {
    id: 32,
    title: "Shinseiki Evangelion Movie: Air/Magokoro wo, Kimi ni",
    slug: "shinseiki-evangelion-movie-airmagokoro-wo-kimi-ni",
    genres: ["Avant Garde", "Drama", "Sci-Fi", "Suspense"],
    type: "Movie",
    status: "Finished Airing",
    year: 1997,
  },
  {
    id: 59845,
    title: "Kaoru Hana wa Rin to Saku",
    slug: "kaoru-hana-wa-rin-to-saku",
    genres: ["Drama", "Romance"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 32983,
    title: "Natsume Yuujinchou Go",
    slug: "natsume-yuujinchou-go",
    genres: ["Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2016,
  },
  {
    id: 31757,
    title: "Kizumonogatari II: Nekketsu-hen",
    slug: "kizumonogatari-ii-nekketsu-hen",
    genres: ["Action", "Mystery", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2016,
  },
  {
    id: 12355,
    title: "Ookami Kodomo no Ame to Yuki",
    slug: "ookami-kodomo-no-ame-to-yuki",
    genres: ["Award Winning", "Slice of Life", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2012,
  },
  {
    id: 10379,
    title: "Natsume Yuujinchou San",
    slug: "natsume-yuujinchou-san",
    genres: ["Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2011,
  },
  {
    id: 40776,
    title: "Haikyuu!! To the Top Part 2",
    slug: "haikyuu-to-the-top-part-2",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 63019,
    title: "Prism Rondo",
    slug: "prism-rondo",
    genres: ["Drama", "Romance"],
    type: "ONA",
    status: "Finished Airing",
    year: 2026,
  },
  {
    id: 61903,
    title: "Kaguya-sama wa Kokurasetai: Otona e no Kaidan",
    slug: "kaguya-sama-wa-kokurasetai-otona-e-no-kaidan",
    genres: ["Comedy", "Romance"],
    type: "TV Special",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 60557,
    title: "Fanren Xiu Xian Zhuan 4th Season",
    slug: "fanren-xiu-xian-zhuan-4th-season",
    genres: ["Action", "Adventure", "Fantasy"],
    type: "ONA",
    status: "Finished Airing",
    year: 2025,
  },
  {
    id: 36098,
    title: "Kimi no Suizou wo Tabetai",
    slug: "kimi-no-suizou-wo-tabetai",
    genres: ["Drama", "Romance"],
    type: "Movie",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 30484,
    title: "Steins;Gate 0",
    slug: "steinsgate-0",
    genres: ["Drama", "Sci-Fi", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2018,
  },
  {
    id: 49701,
    title: "Doupo Cangqiong: San Nian Zhi Yue",
    slug: "doupo-cangqiong-san-nian-zhi-yue",
    genres: ["Action", "Adventure", "Fantasy"],
    type: "ONA",
    status: "Finished Airing",
    year: 2021,
  },
  {
    id: 7785,
    title: "Yojouhan Shinwa Taikei",
    slug: "yojouhan-shinwa-taikei",
    genres: ["Award Winning", "Comedy", "Mystery", "Romance", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2010,
  },
  {
    id: 437,
    title: "Perfect Blue",
    slug: "perfect-blue",
    genres: ["Avant Garde", "Award Winning", "Drama", "Horror", "Suspense"],
    type: "Movie",
    status: "Finished Airing",
    year: 1998,
  },
  {
    id: 170,
    title: "Slam Dunk",
    slug: "slam-dunk",
    genres: ["Sports"],
    type: "TV",
    status: "Finished Airing",
    year: 1993,
  },
  {
    id: 52034,
    title: "[Oshi no Ko]",
    slug: "oshi-no-ko",
    genres: ["Award Winning", "Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2023,
  },
  {
    id: 28735,
    title: "Shouwa Genroku Rakugo Shinjuu",
    slug: "shouwa-genroku-rakugo-shinjuu",
    genres: ["Drama"],
    type: "TV",
    status: "Finished Airing",
    year: 2016,
  },
  {
    id: 25777,
    title: "Shingeki no Kyojin Season 2",
    slug: "shingeki-no-kyojin-season-2",
    genres: ["Action", "Drama", "Suspense"],
    type: "TV",
    status: "Finished Airing",
    year: 2017,
  },
  {
    id: 11741,
    title: "Fate/Zero 2nd Season",
    slug: "fatezero-2nd-season",
    genres: ["Action", "Fantasy"],
    type: "TV",
    status: "Finished Airing",
    year: 2012,
  },
  {
    id: 578,
    title: "Hotaru no Haka",
    slug: "hotaru-no-haka",
    genres: ["Drama"],
    type: "Movie",
    status: "Finished Airing",
    year: 1988,
  },
  {
    id: 40456,
    title: "Kimetsu no Yaiba Movie: Mugen Ressha-hen",
    slug: "kimetsu-no-yaiba-movie-mugen-ressha-hen",
    genres: ["Action", "Supernatural"],
    type: "Movie",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 60058,
    title: "[Oshi no Ko] 3rd Season",
    slug: "oshi-no-ko-3rd-season",
    genres: ["Drama"],
    type: "TV",
    status: "Currently Airing",
    year: 2026,
  },
  {
    id: 50250,
    title: "Chiikawa",
    slug: "chiikawa",
    genres: ["Slice of Life"],
    type: "TV",
    status: "Currently Airing",
    year: 2022,
  },
  {
    id: 5300,
    title: "Zoku Natsume Yuujinchou",
    slug: "zoku-natsume-yuujinchou",
    genres: ["Slice of Life", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2009,
  },
  {
    id: 40417,
    title: "Fruits Basket 2nd Season",
    slug: "fruits-basket-2nd-season",
    genres: ["Drama", "Romance", "Supernatural"],
    type: "TV",
    status: "Finished Airing",
    year: 2020,
  },
  {
    id: 61322,
    title: "Dr. Stone: Science Future Part 2",
    slug: "dr-stone-science-future-part-2",
    genres: ["Adventure", "Comedy"],
    type: "TV",
    status: "Finished Airing",
    year: 2025,
  },
]

// Export just IDs for generateStaticParams
export const STATIC_ANIME_IDS = STATIC_ANIME_LIST.map(anime => anime.id)

// Get anime by ID
export function getStaticAnimeById(id: number): StaticAnime | undefined {
  return STATIC_ANIME_LIST.find(anime => anime.id === id)
}

// Get all anime IDs for generateStaticParams
export function getStaticAnimeParams() {
  return STATIC_ANIME_LIST.map(anime => ({ id: anime.id.toString() }))
}
